# With walking

## Real data

In [1]:
import pickle

with open('mobiact_realworld.pkl', 'rb') as f:
    x, y, k = pickle.load(f)

print(x.shape, y.shape, k.shape)

(22599, 3, 128) (22599,) (22599,)


In [2]:
from sklearn.model_selection import train_test_split
import torch
import numpy as np

num_df_domains = 61
num_dp_domains = 15

x_src, y_src, k_src = x[k < num_df_domains], y[k < num_df_domains], k[k < num_df_domains]
print(np.unique(k_src))
x_train_src, x_test_src, y_train_src, y_test_src = train_test_split(x_src, y_src, test_size=0.2, random_state=2710, stratify=y_src, shuffle=True)
print(f'Source domain: train {x_train_src.shape}, test {x_test_src.shape}, total {x_src.shape}')

train_src = {'samples': x_train_src, 'labels': y_train_src}
test_src = {'samples': x_test_src, 'labels': y_test_src}

torch.save(train_src, 'train_src.pt')
torch.save(test_src, 'test_src.pt')

x_trg, y_trg, k_trg = x[k >= num_df_domains], y[k >= num_df_domains], k[k >= num_df_domains]
print(np.unique(k_trg))
x_train_trg, x_test_trg, y_train_trg, y_test_trg = train_test_split(x_trg, y_trg, test_size=0.2, random_state=2710, stratify=y_trg, shuffle=True)
print(f'Target domain: train {x_train_trg.shape}, test {x_test_trg.shape}, total {x_trg.shape}')

train_trg = {'samples': x_train_trg, 'labels': y_train_trg}
test_trg = {'samples': x_test_trg, 'labels': y_test_trg}

torch.save(train_trg, 'train_trg.pt')
torch.save(test_trg, 'test_trg.pt')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60]
Source domain: train (8652, 3, 128), test (2164, 3, 128), total (10816, 3, 128)
[61 62 63 64 65 66 67 68 69 70 71 72 73 74 75]
Target domain: train (9426, 3, 128), test (2357, 3, 128), total (11783, 3, 128)


## Synthetic data

In [3]:
import pickle

with open('mobiact_realworld_marw01.pkl', 'rb') as f:
    x_syn, x_real, y_syn, y_real, k_syn, k_real = pickle.load(f)

print(x_syn.shape, x_real.shape, y_syn.shape, y_real.shape, k_syn.shape, k_real.shape)

(11520, 3, 128) (8903, 3, 128) (11520,) (8903,) (11520,) (8903,)


In [4]:
import numpy as np

print(np.unique(y_syn))
print(np.unique(k_syn))
print(np.unique(y_real))
print(np.unique(k_real))

[0 1 2 3]
[61 62 63 64 65 66 67 68 69 70 71 72 73 74 75]
[0 1 2 3]
[61 62 63 64 65 66 67 68 69 70 71 72 73 74 75]


In [5]:
from sklearn.model_selection import train_test_split
import torch

for domain in np.unique(k_syn):
    x_syn_dom = x_syn[k_syn == domain]
    y_syn_dom = y_syn[k_syn == domain]

    x_real_dom = x_real[k_real == domain]
    y_real_dom = y_real[k_real == domain]

    print(f'Domain {domain}, x_syn_dom.shape: {x_syn_dom.shape}, x_real_dom.shape: {x_real_dom.shape}')

    x_syn_dom_train, x_syn_dom_test, y_syn_dom_train, y_syn_dom_test = train_test_split(x_syn_dom, y_syn_dom, test_size=0.2, random_state=2710, stratify=y_syn_dom, shuffle=True)
    x_real_dom_train, x_real_dom_test, y_real_dom_train, y_real_dom_test = train_test_split(x_real_dom, y_real_dom, test_size=0.2, random_state=2710, stratify=y_real_dom, shuffle=True)

    train_data_syn = {'samples': x_syn_dom_train, 'labels': y_syn_dom_train}
    test_data_syn = {'samples': x_syn_dom_test, 'labels': y_syn_dom_test}
    train_data_real = {'samples': x_real_dom_train, 'labels': y_real_dom_train}
    test_data_real = {'samples': x_real_dom_test, 'labels': y_real_dom_test}

    torch.save(train_data_syn, f'train_syn_{domain}.pt')
    torch.save(test_data_syn, f'test_syn_{domain}.pt')
    torch.save(train_data_real, f'train_real_{domain}.pt')
    torch.save(test_data_real, f'test_real_{domain}.pt')

Domain 61, x_syn_dom.shape: (760, 3, 128), x_real_dom.shape: (685, 3, 128)
Domain 62, x_syn_dom.shape: (728, 3, 128), x_real_dom.shape: (618, 3, 128)
Domain 63, x_syn_dom.shape: (812, 3, 128), x_real_dom.shape: (676, 3, 128)
Domain 64, x_syn_dom.shape: (732, 3, 128), x_real_dom.shape: (318, 3, 128)
Domain 65, x_syn_dom.shape: (828, 3, 128), x_real_dom.shape: (653, 3, 128)
Domain 66, x_syn_dom.shape: (748, 3, 128), x_real_dom.shape: (625, 3, 128)
Domain 67, x_syn_dom.shape: (728, 3, 128), x_real_dom.shape: (410, 3, 128)
Domain 68, x_syn_dom.shape: (780, 3, 128), x_real_dom.shape: (702, 3, 128)
Domain 69, x_syn_dom.shape: (744, 3, 128), x_real_dom.shape: (633, 3, 128)
Domain 70, x_syn_dom.shape: (752, 3, 128), x_real_dom.shape: (594, 3, 128)
Domain 71, x_syn_dom.shape: (792, 3, 128), x_real_dom.shape: (676, 3, 128)
Domain 72, x_syn_dom.shape: (752, 3, 128), x_real_dom.shape: (643, 3, 128)
Domain 73, x_syn_dom.shape: (776, 3, 128), x_real_dom.shape: (641, 3, 128)
Domain 74, x_syn_dom.shap

# Without walking

In [ ]:
import pickle
import numpy as np

with open('mobiact_realworld.pkl', 'rb') as f:
    x, y, k = pickle.load(f)
with open('mobiact_realworld_fs.pkl', 'rb') as f:
    fs = pickle.load(f)

# Filter out observations where y is 0
mask = y != 0
x = x[mask]
y = y[mask]
k = k[mask]
fs = fs[mask]

# Remap y to start from 0
unique_y = np.unique(y)
y_remap = {old: new for new, old in enumerate(unique_y)}
y = np.array([y_remap[val] for val in y])

print(x.shape, y.shape, k.shape, fs.shape)

In [ ]:
from sklearn.model_selection import train_test_split
import torch
import numpy as np

num_df_domains = 15
num_dp_domains = 61

x_src, y_src, k_src = x[k <= num_df_domains], y[k <= num_df_domains], k[k <= num_df_domains]
print(np.unique(k_src))
x_train_src, x_test_src, y_train_src, y_test_src = train_test_split(x_src, y_src, test_size=0.2, random_state=2710, stratify=y_src, shuffle=True)
print(f'Source domain: train {x_train_src.shape}, test {x_test_src.shape}')

train_src = {'samples': x_train_src, 'labels': y_train_src}
test_src = {'samples': x_test_src, 'labels': y_test_src}

torch.save(train_src, 'train_src_nowal.pt')
torch.save(test_src, 'test_src_nowal.pt')

x_trg, y_trg, k_trg = x[k > num_df_domains], y[k > num_df_domains], k[k > num_df_domains]
print(np.unique(k_trg))
x_train_trg, x_test_trg, y_train_trg, y_test_trg = train_test_split(x_trg, y_trg, test_size=0.2, random_state=2710, stratify=y_trg, shuffle=True)
print(f'Target domain: train {x_train_trg.shape}, test {x_test_trg.shape}')

train_trg = {'samples': x_train_trg, 'labels': y_train_trg}
test_trg = {'samples': x_test_trg, 'labels': y_test_trg}

torch.save(train_trg, 'train_trg_nowal.pt')
torch.save(test_trg, 'test_trg_nowal.pt')